apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:  # hard rule
        nodeSelectorTerms:
          - matchExpressions:
              - key: hardware
                operator: In
                values:
                - "gpu"
      # preferedDuringSchedulingIgnoreDuringExecution:  # soft rule
      #   nodeSelectorTerms:
      #     - matchExpressions:
      #         - key: hardware
      #           operator: In
      #           values:
      #           - "gpu"
  containers:
    - name: nginx
      image: nginx
  # tolerations:
  #   - key: "hardware"
  #     value: "gpu"
  #     operator: "Equal"
  #     effect: "NoSchedule"