apiVersion: v1
kind: Pod
metadata:
  name: nginx
  spec:
    containers:
      - name: nginx
        image: nginx
    tolerations:
      - keys: "hardware"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"